Fix compile errors for macOS 10.12
On macOS Sierra, running 'make bench' gives compile errors in all of the
verilator testbenches, complaining about an ambiguous call to dump
(because there is no dump() defined for a uint64_t, or clang++ doesn't
define vluint64_t to be the same as uint64_t). This patch fixes those
compiler errors

Compiler error:

mpy_tb.cpp:113:13: error: call to member function 'dump' is ambiguous
                        m_trace->dump((uint64_t)(10ul*m_tickcount+5));
                        ~~~~~~~~~^~~~
/usr/local/Cellar/verilator/3.926/share/verilator/include/verilated_vcd_c.h:434:10: note: candidate function
    void dump (vluint64_t timeui) { m_sptrace.dump(timeui); }
         ^
/usr/local/Cellar/verilator/3.926/share/verilator/include/verilated_vcd_c.h:437:10: note: candidate function
    void dump (double timestamp) { dump(static_cast<vluint64_t>(timestamp)); }
         ^
/usr/local/Cellar/verilator/3.926/share/verilator/include/verilated_vcd_c.h:438:10: note: candidate function
    void dump (vluint32_t timestamp) { dump(static_cast<vluint64_t>(timestamp)); }
         ^
/usr/local/Cellar/verilator/3.926/share/verilator/include/verilated_vcd_c.h:439:10: note: candidate function
    void dump (int timestamp) { dump(static_cast<vluint64_t>(timestamp)); }

Clang version:
$ clang++ -v
    Apple LLVM version 9.0.0 (clang-900.0.38)
    Target: x86_64-apple-darwin16.7.0
    Thread model: posix

$ verilator --version
    Verilator 3.926 2018-08-22 rev UNKNOWN_REV